name: Continuous Integration
on:
  push:
    branches:
        - master
    paths-ignore:
        - '**.md'
  pull_request:
    paths-ignore:
        - '**.md'
 
jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test . 
    - run: docker run todo-app:test   

  production:
    name: Production
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push' 
    steps:
    - uses: actions/checkout@v2
      
    - name: Setting up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Authenticating DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pushing to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        target: production
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/todoapp:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/todoapp:buildcache,mode=max

    - name: Deploying to Azure
      run: curl -dH -X POST ${{secrets.WEBHOOK_URL}}
      
       

#I have not dont the module 8 yet. I need to use the curl command in future 
 #final step 
#curl -dH -X POST ${{secrets.WEBHOOK_URL}}