name: Continuous Integration
on:
  push:
    branches:
        - master
    paths-ignore:
        - '**.md'
  pull_request:
    paths-ignore:
        - '**.md'
 
jobs: 
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --target test --tag todo-app:test . 
    - run: docker run todo-app:test   

#I have not dont the module 8 yet. I need to use the curl command in future 
 #final step 
#curl -dH -X POST ${{secrets.WEBHOOK_URL}}